### ISSUE TITLE
The whole system breaks when I run Enve installed from flatpak

### ISSUE THREAD

**Issue by Gilraiser** [flathub/io.github.maurycyliebner.enve#2]
Enve 0.0.0c-4706637. Archlinux 64x

Hello, warm regards. Thank you for developing this software. Basically the entire system freezes seconds after running the program and displaying the window. I use the Archlinux 64-bit operating system.

I hope the information is useful.

Thank you.

**Comment by eszlari** [comment]
* GPU?
* output of `journalctl`?

**Comment by Gilraiser** [comment]
Hi. I changed the nvidia nouveau driver to the nvidia driver. Apparently it didn't have support for opencl. Flatpak works just like appImage. Thank you very much, I did not know this software. I would like to export to SVG stream. I tried but I couldn't do it.

**Comment by MaurycyLiebner** [comment]
> I would like to export to SVG stream. I tried but I couldn't do it.

Please be more specific.

**Comment by MaurycyLiebner** [comment]
This issue is probably related to MaurycyLiebner/enve#6

**Comment by Gilraiser** [comment]
@MaurycyLiebner. I made a video to explain what happens. I also upload the files where I made another animation. Thank you very much for creating this software.

https://youtu.be/WBh1CJMYcds

[ejemplo-enve.svg.zip](https://github.com/flathub/io.github.maurycyliebner.enve/files/4659301/ejemplo-enve.svg.zip)
[enve-ejemplo.ev.zip](https://github.com/flathub/io.github.maurycyliebner.enve/files/4659302/enve-ejemplo.ev.zip)

**Comment by MaurycyLiebner** [comment]
Animated SVGs are not supported by Inkscape.
If you want to preview the resulting SVG you have to open it in a web browser.
Does this solve your issue with SVGs?

**Comment by Gilraiser** [comment]
Hello, I apologize for my ignorance. I didn't know there was animated svg. What I was looking for was a sequence of images in svg that is very useful to me. Again, thank you very much. I'm going to test this animated svg more thoroughly.
